version: '3.8'

services:
    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        expose:
            - ${DB_PORT}
        volumes:
            - my-db:/var/lib/mysql

volumes:
    my-db:
